### ISSUE TITLE
As a user, I would like to be able to view events near me based upon my location data, so that I can view their information and location

### ISSUE THREAD

**Issue by bradleyknutson** [kbrowngithub/Project1#10]
AC:

- [ ] Utilize location data from Open Street Maps to locate nearby outdoor events
- [ ] Display nearby events to the user
- [ ] Display in list form with a maximum number of returns.

**Comment by kbrowngithub** [comment]
Using the Ticketmaster API upcoming events are now listed on the Venues Panel of the web page.
